version: '3.7'

services:
  karnak:
    container_name: karnak
    image: osirixfoundation/karnak:${KARNAK_VERSION}
    ports:
      - "${DICOM_LISTENER_PORT}:11119"
      - "${KARNAK_WEB_PORT}:8081"
    environment:
      KARNAK_WAIT_FOR: karnak-db:5432
    env_file: karnak.env
    depends_on:
      - karnak-db
    secrets:
      - postgres_karnak_password
      - mainzellisteApiKey
      - karnak_hmac_key
      - karnak_login_password
    extra_hosts:
      - "demo.kheops.online:10.5.5.32"

  karnak-db:
    container_name: karnak-db
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=karnak
      - POSTGRES_USER=karnak
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_karnak_password
    volumes:
      - karnak-db-data:/var/lib/postgresql/data
    secrets:
      - postgres_karnak_password

  mainzelliste-db:
    container_name: mainzelliste-db
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD_FILE=/run/secrets/mainzellisteDbPassword
    volumes:
      - mainzelliste-db-data:/var/lib/postgresql/data
    secrets:
      - mainzellisteDbPassword

  mainzelliste:
    container_name: mainzelliste
    image: osirixfoundation/karnak-mainzelliste:latest
    env_file: mainzelliste.env
    secrets:
      - mainzellisteDbPassword
      - mainzellisteApiKey
      - mainzellistePIDK1
      - mainzellistePIDK2
      - mainzellistePIDK3
    depends_on:
      - mainzelliste-db

secrets:
  karnak_login_password:
    file: secrets/karnak_login_password
  karnak_hmac_key:
    file: secrets/karnak_hmac_key
  postgres_karnak_password:
    file: secrets/karnak_postgres_password
  mainzellisteDbPassword:
    file: secrets/mainzelliste_postgres_password
  mainzellisteApiKey:
    file: secrets/mainzelliste_api_key
  mainzellistePIDK1:
    file: secrets/mainzelliste_pid_k1
  mainzellistePIDK2:
    file: secrets/mainzelliste_pid_k2
  mainzellistePIDK3:
    file: secrets/mainzelliste_pid_k3

volumes:
  mainzelliste-db-data:
  karnak-db-data:
