version: '3.7'

services:
  karnak:
    container_name: karnak
    image: osirixfoundation/karnak:v0.9.3.1
    ports:
      - "11119:11119"
    environment:
      KARNAK_WAIT_FOR: karnak-db:5432
    env_file: karnak.env
    depends_on:
      - karnak-db
    logging:
      driver: json-file
      options:
        max-size: "10m"
    secrets:
      - postgres_karnak_password
      - mainzellisteApiKey
      - karnak_login_password
    networks:
      - reverseproxy
      - karnak-data
      - mainzelliste
      - kheops

  karnak-db:
    container_name: karnak-db
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=karnak
      - POSTGRES_USER=karnak
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_karnak_password
    volumes:
      - karnak-db-data:/var/lib/postgresql/data
    secrets:
      - postgres_karnak_password
    networks:
      - karnak-data

  mainzelliste-db:
    container_name: mainzelliste-db
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=mainzelliste
      - POSTGRES_USER=mainzelliste
      - POSTGRES_PASSWORD_FILE=/run/secrets/mainzellisteDbPassword
    volumes:
      - mainzelliste-db-data:/var/lib/postgresql/data
    secrets:
      - mainzellisteDbPassword
    networks:
      - mainzelliste-data

  mainzelliste:
    container_name: mainzelliste
    image: osirixfoundation/karnak-mainzelliste:extid
    env_file: mainzelliste.env
    secrets:
      - mainzellisteDbPassword
      - mainzellisteApiKey
      - mainzellistePIDK1
      - mainzellistePIDK2
      - mainzellistePIDK3
    depends_on:
      - mainzelliste-db
    networks:
      - mainzelliste
      - mainzelliste-data

secrets:
  karnak_login_password:
    file: secrets/karnak_login_password
  postgres_karnak_password:
    file: secrets/karnak_postgres_password
  mainzellisteDbPassword:
    file: secrets/mainzelliste_postgres_password
  mainzellisteApiKey:
    file: secrets/mainzelliste_api_key
  mainzellistePIDK1:
    file: secrets/mainzelliste_pid_k1
  mainzellistePIDK2:
    file: secrets/mainzelliste_pid_k2
  mainzellistePIDK3:
    file: secrets/mainzelliste_pid_k3

volumes:
  mainzelliste-db-data:
  karnak-db-data:

networks:
  reverseproxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.100.0/24"
  karnak-data:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.101.0/24"
  mainzelliste:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.102.0/24"
  mainzelliste-data:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.103.0/24"
  kheops:
    external:
      name: kheops_kheops_network
